name: Graal Java CI

on:
  push:
    branches: 
      - "master"
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GH_TOKEN }}
        native-image-job-reports: 'true'
        cache : 'maven'
        
    - name: Build with Maven
      run: mvn clean package -Pnative

    - name: Run and validate
      run: ./target/html2pdf --help

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html2pdf-${{ matrix.os == 'macos-14' && 'arm64' || 'amd64' }}
        path: |
          ./target/html2pdf

    - name: Rename artifact
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mv ./target/html2pdf ./target/html2pdf-${{ matrix.os == 'macos-14' && 'arm64' || 'amd64' }}

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          ./target/html2pdf-*
        draft: true
        allowUpdates: true
        token: ${{ secrets.GH_TOKEN }}
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
